package com.saasdemo.backend.enums;

public enum TypeOperation {
  ENREGISTER_UN_ADMIN,
  ENREGISTRER_UN_USER,
  DESACTIVER_UN_USER,
  CREER_UN_EXTRAIT_NAISSANCE,
  MODIFIER_UN_EXTRAIT_NAISSANCE,
  SUPPRIMER_UN_EXTRAIT_NAISSANCE,
  CREER_UN_EXTRAIT_MARIAGE,
  MODIFIER_UN_EXTRAIT_MARIAGE,
  SUPPRIMER_UN_EXTRAIT_MARIAGE,
  CREER_UN_CERTIFICAT_DECES,
  MODIFIER_UN_CERTIFICAT_DECES,
  SUPPRIMER_UN_CERTIFICAT_DECES,
  CREATTION_SOUSCRIPTION

    
}