
# Spring Application
spring.application.name=SaasBackend



# Server
server.port=8080
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain
server.compression.min-response-size=128
server.servlet.context-path=/api/etatcivil/v1


# Datasource
spring.datasource.url=jdbc:mysql://localhost:3306/etatcivildb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Dreamcast1985.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# JWT
jwt.key=qsd4qs86fqs54c8qs94d856qs4d8/s4d56qs1d89qs4dx56qs1d86qs4
jwt.expiration=900 000

# Management / Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Info
info.app.name=etat-civil
info.app.description=Application de gestion des états civils
info.app.version=1.0.0

#paystack
paystack.secret.key=sk_test_6efe9bcabf39f953e47c177511d26e5a6c1f192a
paystack.base.url=https://api.paystack.co
